### ISSUE TITLE
svm.train(trainData,cv2.ml.ROW_SAMPLE,response)此行代码运行有问题

### ISSUE THREAD

**Issue by qilei2333** [CoderCIRNO/sift-kmeans-SVM_pic_classify#1]
cv2.error: OpenCV(3.4.2) C:\projects\opencv-python\opencv\modules\ml\src\data.cpp:298: error: (-215:Assertion failed) (layout == ROW_SAMPLE && responses.rows == nsamples) || (layout == COL_SAMPLE && responses.cols == nsamples) in function 'cv::ml::TrainDataImpl::setData'
网上说是  trainData的shape不正确，我的数据集用的是花蕊数据集，打印出来的shape是（676，50）,不知道该怎么改了

**Comment by CoderCIRNO** [comment]
我设置的训练集大小是150，但676不是150的整数倍，你检查一下是不是有些类别里不足150张图片，或者是什么其他原因导致了这个结果
如果确定是训练集未填满，建议把训练集大小调低，适配自己的数据集

**Comment by qilei2333** [comment]
很强，我评论之后就发现是这个问题了，但是我检测的时候，检测精度百分之百，这。。。正常吗

**Comment by CoderCIRNO** [comment]
这种情况很可能是误把训练集拿来测试，否则就是因为测试集太小造成的巧合，，
